### ISSUE TITLE
How can I align the table?

### ISSUE THREAD

**Issue by mihalt** [pri22296/beautifultable#19] opened 2018-01-02 19:33 UTC
Hello! The problem on screen. How can I align it?

![image](https://user-images.githubusercontent.com/30621622/34497110-cedfdea8-f004-11e7-8536-33a7a50b0f2c.png)

**Comment by pri22296** [comment] 2018-01-03 13:36
@mihalt This shouldn't have happened. Could you share the code snippet used to generate the above table so that I can reproduce this locally?

**Comment by mihalt** [comment] 2018-01-03 19:02
It is like this:
```
>>>l = ['StatTrak™ Desert Eagle | Bronze Deco (Field-Tested)', 'StatTrak™ Desert Eagle | Bronze Deco (Field-Tested)']
>>>table = BeautifulTable()
table.append_column('First_column', l)
![image](https://user-images.githubusercontent.com/30621622/34535050-66126bfa-f0c9-11e7-99df-8a3411b4b345.png)
```


And one more problem, that table is some shifts after \n

**Comment by pri22296** [comment] 2018-01-04 09:08
I wasn't able to reproduce this. I got the following table locally.

![capture](https://user-images.githubusercontent.com/11555869/34556334-de1f080a-f15b-11e7-8713-ac3174516c60.PNG)

Are you on the latest version? If not, I would suggest to update to the latest version and see if the issue still persists.

Also about the table shifting after ```\n```, that isn't a bug actually. When you pass multiple parameters to print statement, It adds the default seperator(whitespace) between them. That is why you are seeing the table not starting from the correct position. To fix that, use the following snippet.

```print('\n', table, sep='')```

**Comment by mihalt** [comment] 2018-01-04 09:58
yes, this problems are only in pycharm

**Comment by pri22296** [comment] 2018-01-04 10:52
I see. Could you try the following and check if either method works?

1. Try running the code again but with the `™` symbol removed from the text.
or
2. Try changing the font type in your editor to a [monospaced](https://en.wikipedia.org/wiki/Monospaced_font) font.

**Comment by mihalt** [comment] 2018-01-05 07:20
1. Without ™ it is ok
2. I have had monospace now

**Comment by pri22296** [comment] 2018-01-11 04:54
Sorry for the late reply. I investigated this issue. This indeed seems to be the case with PyCharm. However, even though the table seems unaligned, the printed table has same number of characters for every line. Hence this is an issue with PyCharm's output console. I haven't used pycharm much, so I couldn't find a fix for this. I am removing the bug label as this isn't technically a bug with beautifultable.

**Comment by mihalt** [comment] 2018-01-11 09:29
may be you write ticket to pycharm?

**Comment by pri22296** [comment] 2018-01-11 13:04
Ok, It seems the issue is with the specific font named `Monospaced`. Choosing any other monospace font such as `source code pro`, `Courier New`, etc fixes this for me. Can you confirm it fixes this for you too?

**Closed** 2018-01-20 19:16 UTC
